Migrated to test-r

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -40,7 +40,12 @@ jobs:
     - name: Clippy
       run: cargo clippy -- -Dwarnings      
     - name: Tests
-      run: cargo test --all-features
+      run: cargo test --tests --all-features -- --format junit --logfile target/report.xml
+    - name: Publish Test Report
+      uses: mikepenz/action-junit-report@v4
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: '**/target/report-*.xml'
 
   publish:
     needs: [ build ]
