Updated testcontainers

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -240,7 +240,13 @@ jobs:
         run: cargo make --profile ci unit-tests
       - name: Check formatting and clippy rules
         run: cargo make --profile ci check
-
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/report-*.xml'
+          detailed_summary: true
+          include_passed: true
   worker-tests-group1:
     runs-on: ubuntu-latest-large
     name: worker-tests-group1
@@ -271,6 +277,13 @@ jobs:
       - name: Worker Executor integration tests
         run: cargo make --profile ci worker-executor-tests-group1
         timeout-minutes: 20
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/report-*.xml'
+          detailed_summary: true
+          include_passed: true
   worker-tests:
     needs: [ worker-tests-group1 ]
     runs-on: ubuntu-latest-large
@@ -314,6 +327,13 @@ jobs:
       - name: Worker Executor integration tests
         run: cargo make --profile ci worker-executor-tests-${{ matrix.group.name }}
         timeout-minutes: 40
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/report-*.xml'
+          detailed_summary: true
+          include_passed: true
   integration-tests:
     runs-on: ubuntu-latest-large
     steps:
@@ -346,6 +366,13 @@ jobs:
           QUIET: 1
         run: cargo make --profile ci integration-tests
         timeout-minutes: 30
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/report-*.xml'
+          detailed_summary: true
+          include_passed: true
   cli-tests:
     runs-on: ubuntu-latest-large
     steps:
@@ -378,6 +405,13 @@ jobs:
           QUIET: 1
         run: cargo make --profile ci cli-tests
         timeout-minutes: 35
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/report-*.xml'
+          detailed_summary: true
+          include_passed: true
   sharding-tests:
     runs-on: ubuntu-latest-large
     steps:
@@ -410,6 +444,13 @@ jobs:
           QUIET: 1
         run: cargo make --profile ci sharding-tests
         timeout-minutes: 30
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v4
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/target/report-*.xml'
+          detailed_summary: true
+          include_passed: true
   publish:
     needs:
       [
